### ISSUE TITLE
Request to be able to specify readout window when using HSI pass-through mode

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/trigger#119]
I've noticed that the configurations generated with the following two commands result in data files that have TriggerRecords with the same readout window, even though I've requested different readout windows with the "-b" and "-a" options:
```
daqconf_multiru_gen --enabled-hsi-signals 128 --hsi-signal-emulation-mode 2 -t 1.0 --hsi-trigger-type-passthrough --use-fake-data-producers -b 2000 -a 2000 mdapp_fdp_ba2000

daqconf_multiru_gen --enabled-hsi-signals 128 --hsi-signal-emulation-mode 2 -t 1.0 --hsi-trigger-type-passthrough --use-fake-data-producers -b 5000 -a 5000 mdapp_fdp_ba5000
```
This seems to be related to the use of the `--hsi-trigger-type-passthrough` option.

And, it seems to be related to the fact that the C++ code is using the "s0" before and after times, as shown here:

- [https://github.com/DUNE-DAQ/trigger/blob/0fad6ebf6087671d9cd5347c1e2f16a09bc21b9f/plugins/TimingTriggerCandidateMaker.cpp#L41](https://github.com/DUNE-DAQ/trigger/blob/0fad6ebf6087671d9cd5347c1e2f16a09bc21b9f/plugins/TimingTriggerCandidateMaker.cpp#L41)
- [https://github.com/DUNE-DAQ/trigger/blob/0fad6ebf6087671d9cd5347c1e2f16a09bc21b9f/plugins/TimingTriggerCandidateMaker.cpp#L74](https://github.com/DUNE-DAQ/trigger/blob/0fad6ebf6087671d9cd5347c1e2f16a09bc21b9f/plugins/TimingTriggerCandidateMaker.cpp#L74)

whereas the configuration is only setting the before and after times for "s1" and "s2" to the values specified with -b and -a, as shown here:

- [https://github.com/DUNE-DAQ/daqconf/blob/7d809a794fa7ef7753e0727327f4d92a47f9b392/python/daqconf/apps/trigger_gen.py#L150](https://github.com/DUNE-DAQ/daqconf/blob/7d809a794fa7ef7753e0727327f4d92a47f9b392/python/daqconf/apps/trigger_gen.py#L150)

It would be helpful to be able to set the readout window before and after times even when the HSI pass-through mode is enabled.

**Comment by philiprodrigues** [comment]
Thanks for the detailed description, which made this straightforward to fix. The minimal way to do so was to modify the configuration, which I've done in https://github.com/DUNE-DAQ/daqconf/pull/47
