### ISSUE TITLE
Is it expected that TC fragments will have different size in long-window-readout runs?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/trigger#129]
I see that the TC Fragment has size 136 when I run a basic system, but I see a TC Fragment size of 80 when I run a long-window-readout run.  Is that expected?  I suspect that a size of 80 means header-only, so I wonder if the TC Fragment payload is missing in the long-window-readout case...

Some possibly useful commands:
```
daqconf_multiru_gen -d ./frames.bin -o . -s 10 -n 2 -b 1000 -a 1000 --host-ru localhost mdapp_basic

daqconf_multiru_gen -d ./frames.bin -o . -s 10 -n 2 -b 20000 -a 20000 -t 0.2 --latency-buffer-size 200000 --host-ru localhost --host-df localhost --max-trigger-record-window 13500 mdapp_lwr

curl -o frames.bin -O https://cernbox.cern.ch/index.php/s/7qNnuxD8igDOVJT/download

nanorc mdapp_basic boot ${USER}_test init conf start 101 wait 20 stop wait 2 scrap terminate; keepAlive

nanorc mdapp_lwr boot ${USER}_test init conf start 201 wait 20 stop wait 2 scrap terminate; keepAlive

h5dump-shared -H swtest_run000101_0000_dataflow0_20220524T172057.hdf5 | grep -A4 '"Trigger"' | tail

h5dump-shared -H swtest_run000201_0000_dataflow0_20220524T172318.hdf5 | grep -A4 '"Trigger"' | tail
```

**Comment by philiprodrigues** [comment]
80 is an empty fragment, so there's a problem here. I will investigate

**Comment by philiprodrigues** [comment]
What I see with the long-readout window configuration is that there are three `TriggerRecord` slices(?) in the HDF5 file per trigger number. The first one has a trigger candidate dataset with size 136 (ie, there is a trigger candidate in this slice), while the other two have trigger candidate datasets with size 80 (ie, empty fragment). Abridged output from `h5dump`:

```
   GROUP "TriggerRecord00003.0000" {
      GROUP "Trigger" {
         GROUP "Region20000" {
            DATASET "Element00000" {
               DATATYPE  H5T_STD_I8LE
               DATASPACE  SIMPLE { ( 136, 1 ) / ( 136, 1 ) }
            }
         }
      }
   }
   GROUP "TriggerRecord00003.0001" {
      GROUP "Trigger" {
         GROUP "Region20000" {
            DATASET "Element00000" {
               DATATYPE  H5T_STD_I8LE
               DATASPACE  SIMPLE { ( 80, 1 ) / ( 80, 1 ) }
            }
         }
      }
   }
   GROUP "TriggerRecord00003.0002" {
      GROUP "Trigger" {
         GROUP "Region20000" {
            DATASET "Element00000" {
               DATATYPE  H5T_STD_I8LE
               DATASPACE  SIMPLE { ( 80, 1 ) / ( 80, 1 ) }
            }
         }
      }
   }
```

Do the `.0001` and `.0002` slices(?) correspond to different time windows? If so, then I guess it's expected that the trigger candidate is only returned in the first window and not the others.

**Comment by bieryAtFnal** [comment]
For long-window-readout triggers, the readout of the data is broken up into a sequence of adjacent (in time) windows and the data is stored in a sequence of TriggerRecords.  Those TriggerRecords all have the same trigger number (since they are all belong to the same trigger) but different sequence numbers.  So, yes, it might be useful to think of the sequence of TriggerRecords that are created as part of a LWR trigger as time slices, although we don't formally label them as such.

I'm not remembering where in the trigger the readout window for each trigger is specified (configured).  If it is in the MLT, then I can imagine that a TriggerCandidate corresponds to a particular instant in time, or maybe a fairly small interval.  So, I could see where a TriggerDecision that has a long readout window that gets split into a sequence of DataRequests might only match the TC in one of the windows.  If this is true, then maybe all we need to do is advertise to users that the TC will only be non-empty in one TriggerRecord sequence elements...

**Comment by philiprodrigues** [comment]
Thanks for the explanation of the trigger record sequence. As you say, the TriggerCandidate is selected based on the candidate timestamp, so it can only appear in one readout window (assuming the windows don't overlap). So I think we just have to advertise the situation to users, as you say.
