### ISSUE TITLE
No Data & Trigger Matching Empty Fragments

### ISSUE THREAD

**Issue by CharlieBatchelor** [DUNE-DAQ/trigger#168]
During a software TP generation run of integration week, we saw errors of the following type which follow one another in quick succession. Looking further down the same log file, we also see that a subset of 6 / 20 input queues delivered no `TPSets` during the run. This as we might now expect reproduced the `cardinality` / `completeness` problem, where we see the queue errors at the end of that run. Investigation is needed.

`2022-Nov-17 21:28:21,777 WARNING [dunedaq::readoutlibs::DefaultRequestHandlerModel<ReadoutType, LatencyBufferType>::RequestResult dunedaq::readoutlibs::DefaultRequestHandlerModel<ReadoutType, LatencyBufferType>::data_request(dunedaq::dfmessages::DataRequest, bool) [with ReadoutType = dunedaq::trigger::TPBuffer::TPWrapper; LatencyBufferType = dunedaq::readoutlibs::SkipListLatencyBufferModel<dunedaq::trigger::TPBuffer::TPWrapper>; RequestResult = dunedaq::readoutlibs::RequestHandlerConcept<dunedaq::trigger::TPBuffer::TPWrapper, dunedaq::readoutlibs::SkipListLatencyBufferModel<dunedaq::trigger::TPBuffer::TPWrapper> >::RequestResult] at /nfs/sw/dunedaq/dunedaq-v3.2.1-integration/sourcecode/readoutlibs/include/readoutlibs/models/detail/DefaultRequestHandlerModel.hxx:577] SourceID[subsystem: Trigger id: 11] Request on empty buffer: Data not found`

`2022-Nov-17 21:28:21,777 WARNING [dunedaq::readoutlibs::DefaultRequestHandlerModel<ReadoutType, LatencyBufferType>::RequestResult dunedaq::readoutlibs::DefaultRequestHandlerModel<ReadoutType, LatencyBufferType>::data_request(dunedaq::dfmessages::DataRequest, bool) [with ReadoutType = dunedaq::trigger::TPBuffer::TPWrapper; LatencyBufferType = dunedaq::readoutlibs::SkipListLatencyBufferModel<dunedaq::trigger::TPBuffer::TPWrapper>; RequestResult = dunedaq::readoutlibs::RequestHandlerConcept<dunedaq::trigger::TPBuffer::TPWrapper, dunedaq::readoutlibs::SkipListLatencyBufferModel<dunedaq::trigger::TPBuffer::TPWrapper> >::RequestResult] at /nfs/sw/dunedaq/dunedaq-v3.2.1-integration/sourcecode/readoutlibs/include/readoutlibs/models/detail/DefaultRequestHandlerModel.hxx:588] SourceID[subsystem: Trigger id: 1] Trigger Matching result with empty fragment:`

The relevant log file is `log_2022-11-17_212324_trigger_5934.txt` on np04 server 018.

**Comment by CharlieBatchelor** [comment]
This might be a feature of the SW TPG and FW TPG pulser runs. Recreated in FW TPG run 18201, Grafana example message:

`SourceID[subsystem: Trigger id: 20] Trigger Matching result with empty fragment: TS match result on link 20: Trigger number=596 Oldest stored TS=104400762891687653 Start of window TS=104400762878612297 End of window TS=104400762878874441 Estimated newest stored TS=16107026128616528031 Requestor=fragments_to_dataflow0
`

Issue Name: `readoutlibs::TrmWithEmptyFragment`

It appears not _all_ triggers are receiving this error.  Perhaps we need to increase the buffer timeout for raw data for these runs?

**Comment by CharlieBatchelor** [comment]
These messages are being observed in electronic noise SW TPG runs on the VDCB, using 12 links.

**Comment by CharlieBatchelor** [comment]
Tardy input messages are reduced by increasing the `max_latency_ms` variable for the TPZippers. We still need to look into:

`SourceID[subsystem: Trigger id: 4] Request on empty buffer: Data not found`
`Trigger Matching result with empty fragment:`
messages.

Eg:

**`2023-Feb-01 12:30:37,147 WARNING [dunedaq::readoutlibs::DefaultRequestHandlerModel<ReadoutType, LatencyBufferType>::RequestResult dunedaq::readou     tlibs::DefaultRequestHandlerModel<ReadoutType, LatencyBufferType>::data_request(dunedaq::dfmessages::DataRequest, bool) [with ReadoutType = duned     aq::trigger::TPBuffer::TPWrapper; LatencyBufferType = dunedaq::readoutlibs::SkipListLatencyBufferModel<dunedaq::trigger::TPBuffer::TPWrapper>; Re     questResult = dunedaq::readoutlibs::RequestHandlerConcept<dunedaq::trigger::TPBuffer::TPWrapper, dunedaq::readoutlibs::SkipListLatencyBufferModel     <dunedaq::trigger::TPBuffer::TPWrapper> >::RequestResult] at /nfs/sw/dunedaq/dunedaq-v3.2.2-prep/sourcecode/readoutlibs/include/readoutlibs/model     s/detail/DefaultRequestHandlerModel.hxx:586] SourceID[subsystem: Trigger id: 0] Request on empty buffer: Data not found`**

**Comment by CharlieBatchelor** [comment]
I increased the readout latency buffer size by a factor of 10, all warning messages have been removed. A clean run and stop were observed.

`"latency_buffer_size": 499968 ----> "latency_buffer_size": 4999680`

**Comment by CharlieBatchelor** [comment]
Similarly, no warning messages with double buffer size:
`"latency_buffer_size": 499968 ----> "latency_buffer_size": 999936`

**Comment by CharlieBatchelor** [comment]
Okay, these messages are now being observed in a cooled down Large filled VDCB, on a single link run with 10x `latency_buffer_size` factor. I'm wondering if the data is simply never present, and possibly due to the non-responsive FEMB 3 we have for these runs. The buffer size I am using for this single link run is:

`"latency_buffer_size": 499968 ----> "latency_buffer_size": 4999680`

**Comment by MRiganSUSX** [comment]
Closed after a review at the trigger workshop.
(resolved and tested during march 2023 coldbox run)
