### ISSUE TITLE
Extend trigger emulation capability

### ISSUE THREAD

**Issue by glehmannmiotto** [DUNE-DAQ/trigger#171]
The MLT now requests all elements listed for any trigger decision.
In order to test a mixture of traffic flows in the DAQ, it would be useful to have the option of having a distribution in the requested data sources and readout windows.
We may introduce a special type of TC generator from HSI signals that, instead of a fixed time window and geographic area, would take a distribution (e.g. 1%= all sources + max window, 99%= n APAs + reduced window). This would emulate the behaviour of a trigger selecting cosmics/beam events and low energy RoIs.

**Comment by CharlieBatchelor** [comment]
@glehmannmiotto - If I understand correctly, the specific type TC you mention will in some way tell the MLT the size of the readout window in _WIB link-time_ space. 

Suppose later on that the TC `type` is `LowEnergyEvent`. Should the incoming TC have a predetermined distribution of, say 1 APA and 7000 ticks (for example) centred on the activity that the corresponding `TriggerActivityMaker` found to lead to that TC? This would mean all triggers of type `LowEnergyEvent` have the same readout window size.

Or should this readout window size be a variable number that is determined within the algorithm based somehow on the activity that lead to it? In this case, the window size can be different for different `LowEnergyEvent` TCs.

**Comment by MRiganSUSX** [comment]
This was later extended in [trigger issue230](https://github.com/DUNE-DAQ/trigger/issues/230) and done with [trigger PR242](https://github.com/DUNE-DAQ/trigger/pull/242)
