### ISSUE TITLE
Fix TP Replay App - Endpoint Issue

### ISSUE THREAD

**Issue by CharlieBatchelor** [DUNE-DAQ/trigger#176]
### Overview - `replay_tp_app`

The `replay_tp_app` of trigger is a tool we can use to run the trigger subsystem in isolation, where the input is provided by a simple text file containing TP information. It's particularly useful for developing new trigger algorithms on events that have been simulated in LArSoft alongside their respective TPs that we would expect to see in the VDCB or ProtoDUNE.

The issue that we have is that the app fails to complete configuration, and complains that a specific end point has no consumers. To reproduce, you'll need a sample of input TPs, which can be found here:
`/afs/cern.ch/user/c/cbatchel/public/1000_electron_events.txt` 

The format of this file is the following, where each row corresponds to a single TP:
`<time_start> <time_over_threshold> <time_peak> <channel> <adc_integral> <adc_peak> <det_id> <type>`

### Replicating the Issue
In your run area with the latest `trigger` code, run the following command to attempt configuration generation, making sure to point the `--input-file` to where you have stored the input file above.

`python -m trigger.replay_tp_to_chain --trigger-activity-plugin TriggerActivityMakerLowEnergyEventPlugin --trigger-candidate-plugin TriggerCandidateMakerLowEnergyEventPlugin --trigger-activity-config 'dict(adjacency_threshold=3, window_length=10000, adc_threshold=50000)' --input-file 1000_electron_events.txt replay_json`

The error that you'll see should be one of the following:
`TypeError: ModuleGraph.add_endpoint() got an unexpected keyword argument 'topic'`
Removing 'topic' argument to that function results in:
`ValueError: Connection with name tpsets_rulocalhost_0_link0 has no consumers!`

Which is a result of there being no "in apps" found in the `con_utils` of `daqconf`. Relevant line [here](https://github.com/DUNE-DAQ/daqconf/blob/9dbeae23c9e19d8c9ceffdfc4698c802c192cc7e/python/daqconf/core/conf_utils.py#L310)

**Comment by CharlieBatchelor** [comment]
@MRiganSUSX is able to generate the configuration with a `v3.2.x` build, however the error is produced for me using the latest nightly `N23-01-13`.

**Comment by CharlieBatchelor** [comment]
So the removal of `token_count` entry for the `df` app config and changing [this line](https://github.com/DUNE-DAQ/trigger/blob/8b69073b7eff01519f795abe9c4b663710916e23/python/trigger/replay_tp_to_chain/replay_tp_app.py#L45) for the following gets the configuration generated, and a run working up to the `start_run 1` command. Use the following to achieve _that_ much:

`mgraph.add_endpoint(f"tpsets_rulocalhost_{istream}_link{istream}", f"tpm.output{istream}", "TPSet", Direction.OUT, is_pubsub=True)` 

Unfortunately, it's not immediately clear what the name of the input queue should be set to, and we are unable to find connections with names like `f"tpsets_rulocalhost_{istream}_link{istream}"` at start time. Errors are:

`ERROR [dunedaq::iomanager::ConnectionResponse dunedaq::iomanager::ConfigClient::resolveConnection(const dunedaq::iomanager::ConnectionRequest&) at /tmp/root/spack-stage/spack-stage-iomanager-N23-01-13-kbbkxe7f7rjb3fadtdbhujw6fgncnslu/spack-src/src/network/ConfigClient.cpp:107] Failed to lookup data_requests_for_Trigger_0x00000002 at /getconnection/charlie connect: Connection refused`

`ERROR [dunedaq::iomanager::ConnectionResponse dunedaq::iomanager::ConfigClient::resolveConnection(const dunedaq::iomanager::ConnectionRequest&) at /tmp/root/spack-stage/spack-stage-iomanager-N23-01-13-kbbkxe7f7rjb3fadtdbhujw6fgncnslu/spack-src/src/network/ConfigClient.cpp:107] Failed to lookup tpsets_rulocalhost_0_link0 at /getconnection/charlie connect: Connection refused`

**Comment by CharlieBatchelor** [comment]
@eflumerf, I've spoken to the readout people who have observed the same issue when attempting to create a FW TP test using a TP input file. It's not clear to us how to name these input queues given the first major set of IOManager changes were made. Could you perhaps take a look and provide some advice here? Any guidance would be much appreciated.

**Comment by bieryAtFnal** [comment]
might it also be useful to involve @plasorak ?

**Comment by eflumerf** [comment]
I'm guessing that you aren't using the ConnectivityService, and so you should have `boot.use_connectivity_service` set to false in your JSON.

**Comment by CharlieBatchelor** [comment]
I've changed the `trigger_init.json` to have `boot.use_connectivity_service: false`. Unfortunately, the same error message persists, the final message in the logs I've added below:

>  was caused by: 2023-Jan-16 19:03:52,735 ERROR [typename std::enable_if<dunedaq::serialization::is_serializable<MessageType>::value, MessageType>::type dunedaq::iomanager::Network    ReceiverModel<Datatype>::read_network(const dunedaq::iomanager::Receiver::timeout_t&) [with MessageType = dunedaq::trigger::Set<dunedaq::detdataformats::trigger::TriggerPrimitive>; Datat    ype = dunedaq::trigger::Set<dunedaq::detdataformats::trigger::TriggerPrimitive>; typename std::enable_if<dunedaq::serialization::is_serializable<MessageType>::value, MessageType>::type =     dunedaq::trigger::Set<dunedaq::detdataformats::trigger::TriggerPrimitive>; dunedaq::iomanager::Receiver::timeout_t = std::chrono::duration<long int, std::ratio<1, 1000> >] at /cvmfs/dun    edaq-development.opensciencegrid.org/nightly/N23-01-14/spack-0.18.1-gcc-12.1.0/spack-0.18.1/opt/spack/gcc-12.1.0/iomanager-N23-01-14-mp5vnu4ztayusoflf3uvsw7xn5oux5bn/include/iomanager/ne    twork/NetworkReceiverModel.hpp:112] Connection Instance not found for name tpsets_rulocalhost_0_link0

An example configuration that produces this error is given in the following directory from np04 area, in the case it's useful to anyone here:
`/nfs/sw/DAQ_NP04_HD_TRIGGER_AREA/replay_fix/test/`

**Comment by plasorak** [comment]
`boot.use_connectivity_service` is `False` by default in [here](https://github.com/DUNE-DAQ/daqconf/blob/develop/schema/daqconf/confgen.jsonnet#L52), that gets used as `boot = confgen.boot()` in [here](https://github.com/DUNE-DAQ/trigger/blob/develop/python/trigger/replay_tp_to_chain/__main__.py#L152) but since the `use_connectivity_service` argument is not not specified for [this function](https://github.com/DUNE-DAQ/daqconf/blob/develop/python/daqconf/core/conf_utils.py#L386) in the line after, it uses the default of the function rather than the schema (idem for k8s).

This is fixed here: https://github.com/DUNE-DAQ/trigger/pull/177

Looking in `daqconf_multiru_gen`, I think there is a bit of boiler plate code that we could remove to make sure the user doesn't have to do this: for example, creating a function that takes the `system` and the `boot` configuration out of this [snippet](https://github.com/DUNE-DAQ/daqconf/blob/develop/scripts/daqconf_multiru_gen#L622-L625) that the user would call directly.

**Comment by CharlieBatchelor** [comment]
Pierre's fix allows the configuration to build successfully and a triggering run can be taken to completion with the above described input. Thanks a lot @plasorak
