### ISSUE TITLE
Enhance TPChannelFilter capabilities: Remove known noisy channels?

### ISSUE THREAD

**Issue by CharlieBatchelor** [DUNE-DAQ/trigger#184]
The ongoing vertical drift cold box (VDCB) tests at EHN1 are exhibiting some problems we now think may be related to some known noisy channels producing a very high rate of TPs. It would probably be a good idea to add to the `TPChannelFilter` configuration some dictionary of known noisy channels so that we can remove these ahead of time.

The type of issue that we see currently is that TPBuffers are unable to provide the required data from a data request, and we suspect this might be because the relevant buffer is being filled and emptied too rapidly to hold onto the required TPs long enough. Simply increasing the buffer size and timeout isn't a realistic option since the noisy channels produce TPs at rates many orders of magnitude higher than the average rate.

**Comment by CharlieBatchelor** [comment]
A first attempt has been implemented in the associated branch. A list parameter is passed to the `TPChannelFilter` which will immediately remove channels contained within said list. This was tested in the VDCB tests by removing the very noisy channels pointed out by Roger.

**Comment by MRiganSUSX** [comment]
The issue of noisy channels is now taken care of by readout, therefore we can close this issue (from trigger).
