### ISSUE TITLE
Allow for (partially) overlapping trigger decisions

### ISSUE THREAD

**Issue by glehmannmiotto** [DUNE-DAQ/trigger#190]
The trigger at present considers it an anomaly that trigger decisions may be overlapping, because in some cases it is preferred that TCs are stitched together to form a single decision. This is nevertheless not applicable universally, so the support for overlapping TDs should be reintroduced.

**Comment by glehmannmiotto** [comment]
Is there any update on this?

**Comment by MRiganSUSX** [comment]
Hi @glehmannmiotto. Sorry for the late response. As discussed during DS/PP call, I will work on this as a priority over the next few days.

**Comment by MRiganSUSX** [comment]
Hi @glehmannmiotto. I have made branches that address this. These are:
[trigger:mlt_merging_flag](https://github.com/DUNE-DAQ/trigger/tree/mrigansusx/mlt_merging_flag)
[daqconf:mlt_merging_flag](https://github.com/DUNE-DAQ/daqconf/tree/mrigansusx/mlt_merging_flag)

I've so far tested this on:
- 4 configurations given in setting up dev area instructions
- integration tests: minimal and fake data producer
- my tests using custom trigger candidate maker

Let me know if you want more tests, or whether I should make PRs (and against what). 
Thanks!

**Comment by bieryAtFnal** [comment]
Hi @MRiganSUSX, all,
From my testing so far, this looks good.  
One hopefully minor request would be to suppress the TCOutOfTimeout warning message when TC merging is disabled.  Can that be done?

**Comment by MRiganSUSX** [comment]
Hi @bieryAtFnal, all,
I have now added the change that you requested (same trigger branch). If we don't want any message for the overlap, we can skip the overlap check completely (saving some resources). Let me know if you'd rather have a log message, in which case a small modification would be needed.

I will run some more tests tomorrow with the custom trigger maker and will confirm here.

**Comment by MRiganSUSX** [comment]
Hi @bieryAtFnal, all,
I have run a suite of tests (same as before: example configs, integtests, test with custom trigger maker) and everything works as expected. The one thing to note is that there is now *no* message when there are TDs that overlap (readout windows) - when the merging is turned off.

**Comment by bieryAtFnal** [comment]
I have re-tested the `daqconf mrigansusx/mlt_merging_flag` and `trigger mrigansusx/mlt_merging_flag` branches together, and things look good to me.  

Michal, will you create PRs in `daqconf` and `trigger`?  If so, I'll add my approvals.

**Comment by MRiganSUSX** [comment]
Did that. Thanks.

**Comment by MRiganSUSX** [comment]
This was fixed by [PR218](https://github.com/DUNE-DAQ/trigger/pull/218)
