### ISSUE TITLE
Trigger way too verbose at DEBUG_LEVEL=3

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/trigger#193]
Both of the following lines in the MLT plugin issue a log message every ~10ms when DEBUG_LEVEL>=3. Could the level for these TDEBUG be increased to a higher number?
 - [line 1](https://github.com/DUNE-DAQ/trigger/blob/5d95f7868a2b42d988fba697f532adbe42636785/plugins/ModuleLevelTrigger.cpp#L330)
 - [line 2](https://github.com/DUNE-DAQ/trigger/blob/5d95f7868a2b42d988fba697f532adbe42636785/plugins/ModuleLevelTrigger.cpp#L302)

Thanks

**Comment by MRiganSUSX** [comment]
Hi @plasorak I have (unaware of this request) increased several TLOG message levels in the MLT over the last few weeks. The two lines you mentioned have been bumped to 10 (already in develop). Let me know if that is satisfactory for you. Thanks.
