### ISSUE TITLE
Tidy Up: get_trigger_app()

### ISSUE THREAD

**Issue by CharlieBatchelor** [DUNE-DAQ/trigger#215]
As mentioned in #202:

### get_trigger_app() Tidy Up
The configuration generation for `trigger` is quite messy, and should be tidied up. It essentially does two things:

1. For a given `tp_config` item passed to the function, it generates a `list` of `Modules`. For example, it does things like "For each link, create a `TPChannelFilter` module, `TPBuffer` module..." and so on. 
2. It then connects up all the modules in the list according to what we expect/want the system to run like.

Each step is itself done in quite a convoluted order, and it would make it more readable to generate the configuration in a "top to bottom" sense, based on the trigger flow graph diagrams, at least IMO. Start with the channel filters, to TPSetTees, to heartbeats and buffers, and so on.

**Comment by ArturSztuc** [comment]
No more `get_trigger_app`, moved to OKS, completely different system. Closing.
