### ISSUE TITLE
Testing: what are the exact issues (warnings) when running with 6+ APAs

### ISSUE THREAD

**Issue by MRiganSUSX** [DUNE-DAQ/trigger#238]

**Comment by ArturSztuc** [comment]
@MRiganSUSX do you have more info on this issue? Given it's from 2023 and v4, I would probably close it.

**Comment by MRiganSUSX** [comment]
Hi @ArturSztuc I think the issue was that we once tried running more than 4 APAs - with replay - and there were issues/warnings that came from different trigger modules (so not just replay related makers). 
It was for v4, and it was for replay, and it was before splitting per plane.

So, I think we should still keep in mind scalling beyond np04 4 APAs, but that is a more global issue and this particular one can be closed. I leave the decision to you.

**Comment by ArturSztuc** [comment]
Sounds good, in that case I'm closing this. Cheers!
