### ISSUE TITLE
Convert RTCM/CTCM rates from clock ticks to Hz

### ISSUE THREAD

**Issue by MRiganSUSX** [DUNE-DAQ/trigger#266]
(also possibly other rate parameters).

Currently, the configuration in daqconf works with clock ticks for rate parameters for RTCM and CTCM:
`s.field( "ctcm_trigger_intervals", self.tc_intervals, default=[10000000], doc="Optional list of intervals (clock ticks) for the TC types to be used by the Custom Trigger Candidate Maker (plugin)")`
RTCM:
`s.field( "rtcm_trigger_interval_ticks", self.tc_interval, default=62500000, doc="Interval between triggers in time ticks"),`
type:
`tc_interval:     s.number(   "TCInterval",    "i8", nc(minimum=1, maximum=30000000000), doc="The intervals between TCs that are inserted into MLT by CTCM, in clock ticks"),`

The idea is to change rate parameters to Hz instead as that is easier for general use.

**Comment by ArturSztuc** [comment]
Closing, this was already done for RTCM, and CTCM is being removed from v5. PRs:
1. https://github.com/DUNE-DAQ/trigger/pull/350
2. https://github.com/DUNE-DAQ/trigger/pull/364
