### ISSUE TITLE
OKS: get clock frequency from Session's detector_configuration

### ISSUE THREAD

**Issue by ArturSztuc** [DUNE-DAQ/trigger#278]
_Originally posted by @gcrone in https://github.com/DUNE-DAQ/trigger/pull/277#discussion_r1507934805_

**Comment by ArturSztuc** [comment]
Similar issue for the readoutlibs (@glehmannmiotto @gcrone, https://github.com/DUNE-DAQ/readoutlibs/pull/152#discussion_r1507532071), with an idea to retrieve detector config from ModuleConfiguration. Searching through DUNEDAQ, I only found mention of `ModuleConfiguration` [HERE](https://github.com/DUNE-DAQ/docs/blob/b80a3ac281b90c6a80560d736bbdee443fcf9b2e/docs/packages/appfwk/appfwk.drawio#L79):

**Comment by gcrone** [comment]
ModuleConfiguration is [here](https://github.com/DUNE-DAQ/appfwk/blob/develop/include/appfwk/ModuleConfiguration.hpp) and [here](https://github.com/DUNE-DAQ/appfwk/blob/develop/src/ModuleConfiguration.cpp)

**Comment by ArturSztuc** [comment]
1. `RandomTCMaker` overhaul (merged): https://github.com/DUNE-DAQ/trigger/pull/350
2. `CustomTCMaker: removal (PR pending): https://github.com/DUNE-DAQ/trigger/pull/364

Once the second PR is merged, this issue can be closed.
