### ISSUE TITLE
Some obsolete or missing configuration parameters 

### ISSUE THREAD

**Issue by MRiganSUSX** [DUNE-DAQ/trigger#296]
I've recently done a cleanup of the configurations, and there are some parameters/whole schemas that are unused and there are also some parameters that could/should be configurable but are instead hardcoded. Overview here:
[config.cleanup.ods](https://github.com/DUNE-DAQ/trigger/files/14931976/config.cleanup.ods)
<!DOCTYPE html>

<html>
<head>
	
</head>

<body>

unused schemas |   | weird params in used schemas |  
-- | -- | -- | --
tasetsink.jsonnet | Unused ? | tpchannelfilter: keep_collection | hardcoded true in trigger_gen
faketpcreatorheartbeatmaker.jsonnet | Unused ? | tpchannelfilter: keep_induction | hardcoded true in trigger_gen
tpsetbuffercreator.jsonnet (used in replay?) | Replay ? | tpchannelfilter: max_time_over_threshold | Hardcoded 10000 in trigger_gen
  |   | triggeractivitymaker: window_time | Hardcoded 10000 in trigger_gen
  |   | triggeractivitymaker: buffer_time | calculated but multiplied by constant
  |   | triggerzipper.jsonnet: max_latency_ms | Hardcoded 1000 in trigger_gen
  |   | triggerzipper.jsonnet: tolerate_incompleteness | not set in trigger_gen, used in triggerzipper
  |   | triggerzipper.jsonnet: completeness_tolerance | not set in trigger_gen, used in triggerzipper
  |   | txbuffer.jsonnet | many hardcoded values

</body>
</html>

**Comment by ArturSztuc** [comment]
In v5, trigger schema was cleaned up. Closing
