### ISSUE TITLE
Add line at the end of an FSM transition saying what the available transitions are

### ISSUE THREAD

**Issue by PawelPlesniak** [DUNE-DAQ/trigger#323]

**Comment by MRiganSUSX** [comment]
Should this be a drunc issue instead @PawelPlesniak ?
(also, is it closed or not?)

**Comment by ArturSztuc** [comment]
Not trigger issue, and was tagged as "done". Closing.

**Comment by PawelPlesniak** [comment]
Yes it should be in `drunc` and it is completed. Sorry I don't know why it was here.
