### ISSUE TITLE
OpMon Misusage

### ISSUE THREAD

**Issue by mroda88** [DUNE-DAQ/trigger#335]
There are some abuses of the new monitoring system that lead to some duplicate monitoring information. 
I'm going to use this issues to track them. 

Things like this https://github.com/DUNE-DAQ/trigger/blob/5c3941518286c1d84f5828fb73dea8b2720988e2/plugins/TriggerDataHandlerModule.cpp#L86 are incorrect. The string passed to the register module should not be the name of the registrar, but the name of the objecte that is registered. 
In the specific case of this example, it should be something like `TPConsumer`, following the logic I can understand before the creation of the object. 

Similar cases are 
 * https://github.com/DUNE-DAQ/trigger/blob/5c3941518286c1d84f5828fb73dea8b2720988e2/plugins/TriggerDataHandlerModule.cpp#L99
 * https://github.com/DUNE-DAQ/trigger/blob/5c3941518286c1d84f5828fb73dea8b2720988e2/plugins/TriggerDataHandlerModule.cpp#L113

**Comment by MRiganSUSX** [comment]
Fixed with https://github.com/DUNE-DAQ/trigger/pull/338
