### ISSUE TITLE
Policy on DROP vs BLOCK behavior when `push()` to output queue times out.

### ISSUE THREAD

**Issue by brettviren** [DUNE-DAQ/trigger#39]
The DS modules enact a variety of behavior in response to a timeout on a `push()` to an output queue.  I try to categorize them based on an incomplete survey of the current code:

- spin-warn-block :: the module will *block* by spinning on `ers::warning()`, eg at 10 or 100 Hz, depending on the timeout.  The spin will continue until blockage is cleared.  During the spin, fresh input is not serviced.

- ignore-undefined :: the module will not catch the timeout exception.  I don't know if this counts as DROP or BLOCK as it depends how the ignored exception is handled in the caller.

- warn-drop :: the module warns on each timeout and drops the output until pending output is exhausted.  It then goes back to processing fresh input.

I will argue that the policy should be DROP and not BLOCK.  We can likely argue that but I think it should not be contentious that we have **some** policy.

First, I believe that DAQ must have a line of DROP policy at the interface between UDaq and DS.  DS can not push blockage up in to the UDaq's FPGA, therefore UDaq must DROP if its output queue to DS is full.

Second, in the case that blockage is temporary enough to clear before hitting that DROP line then having BLOCK is equivalent to having deeper queues.  Any argument about riding out rate spikes should be an argument about proper queue depth and not BLOCK vs DROP.

That leaves the case of a persistent blockage where a BLOCK policy causes the blockage to travel upstream until hitting the required line of DROP at the UDaq interface.  Once reached, the DS must drop fresh data.  

Now, assuming the original blockage clears, then the very first thing to happen at the initial blockage location will be that upstream will flood it with queued data.  This data will likely be very similar to what caused the blockage in the first place.  Thus, a new blockage will likely form.

OTOH, a DROP policy will keep fresh data flowing through the graph up to the point of original blockage (where it is dropped).  Then, once that blockage is freed, fresh data is seen and it is likely of a different characteristic than that which caused the initial blockage.   It will also not occur with as much flooding.  So, with a DROP policy, the DAQ will return to normal operation more quickly, keep better and more data.

**Comment by philiprodrigues** [comment]
I definitely agree that we should make the DROP/BLOCK policy explicit, and I agree that DROP sounds like the better of the two options. We should bring this up in a DS meeting to let everyone have their say.

We'll want some common bookkeeping/warning messages to go with dropping output, so I think this implies common code to wrap pushing to a queue. I can think about ways to implement this (unless you have something ready to go?)

**Comment by brettviren** [comment]
In today's DS tech meeting we tentatively decided the policy behavior should be made configurable for every module that will `push()`.  This immediately led to wanting to factor the implementation and standardize its configuration so that each DS module that will `push()` does so in a common manner and with a minimum of repeated coding.

It was then recognized that the ideal center for this factoring would be in the form of a new "smarter" queue "sink" class that is constructed and configured to policy in the "init" handler.  Afterwards the module may use the sink without any care as to what policy it actually enacts.

We want to minimize boilerplate around both the `push()` and the initialization code.  Initialization should look something like:

``` c++
m_mysink = AutoSink<MyMsgType>(...);
```
Some choices are needed to define the constructor args `(...)` interface.  `QueueSink` constructor takes a queue object.  This object is typically provided by the `queue_inst()` helper function which takes the entire `iniobj` config plus the name that the module uses to identify the queue.  The `AutoSink` of course still needs a queue object but also needs the value of the DROP/BLOCK policy.  As there may be many sinks in a module, this policy must also be keyed by the module's name for the sink (and NOT the queue instance name).  Thus it seems right to subsume the call to `queue_inst` into `AutoSink` ctor and have an interface like:

``` c++
m_mysink = AutoSink<MyMsgType>(iniobj, "my_queue_name");
```

In the `operator()` the `DAQModule` would then call `AutoSink::push()` just like `QueueSink::push()`:

``` c++
  m_mysink->push(mymsg, mytimeout);
```

With the difference being that no `try/catch` block is required (nor useful).

But there is a wrinkle.  The above is fine for the "warn-drop" pattern for DROP policy.  A call to `push()` takes at most `mytimeout` and execution returns.  The module may then check the "running" flag to see if its worker thread loop should continue or exit.

For the "spin-warn-block" pattern for BLOCK policy, the `push()` can in principle never return.  We must then broaden the interface to inject communication about the "running" flag.  And so the calling context must look like:

``` c++
  m_mysink->push(mymsg, mytimeout, my_running_flag);
  if (!my_running_flag.load()) {
    break;  // or return, whatever
  }
```

The other problem with `push()` timeouts is how to notify "the world" when they happen.  As long as the downstream blockage remains, the naive timeout handling will lead to two slightly different behaviors, both not great:

- "warn-drop" will flood `ers::warning` at a maximum rate of `1/mytimeout`.  If the natural output rate is lower, then that will set warning flood rate.

- "spin-warn-block" will flood `ers::warning` at `1/mytimeout` even if upstream data is turned off.

What we want then is `AutoSink::push()` to do something smarter.  For example, the `push()` may remember a "last timed out time" and when a timeout occurs, compare current (system) time to that last.  Based on that time delta an exponential back-off on emitting `ers::warnings` can be constructed.

**Comment by ArturSztuc** [comment]
This issue is old/stale, so I will close it.
The system has changed a lot since: we don't have `push()` to the sinks anymore, and we're using the system similar to the one described above. Queues are defined, e.g.:

```cpp
m_sink = get_iom_sender<Object>(cfg->get_outputs()->UID());
```

and then used:

```cpp
if (!m_sink->try_send(std::move(object), iomanager::Sender::s_noblock) {
    ers::warning(ObjectDropped(ERS_HERE, object_args));
    ++m_objects_dropped;
}
