### ISSUE TITLE
Change to `Set<T>` to add `origin` and remove `from_detids`

### ISSUE THREAD

**Issue by brettviren** [DUNE-DAQ/trigger#40]
These are two independent issues but small enough and in the same context to treat together.

The `from_detids` is ill defined and unused and depending on interpretation is redundant with info in `objects` or which may be provided in configuration.

OTOH, the identity of a source aka origin of a `Set<T>` is needed in order to meaningfully aggregate sets from multiple sources.   

In some cases the origin ID may be opaque.  Eg, in zipper, this identity is needed to define logical "streams" from the single input queue.  Other cases, such as TA/TC creators, a semantic meaningful origin may be required.  

After some discussion, the identification of an origin by a `GeoID` seems most reasonable.

This issue will update `Set.hpp` and clear out any uses of `from_detids`.

A larger issue is to set the new `Set<T>::origin` attribute.  Each producer of `Set<T>` is in principle free to set `origin` in any way.  But, most likely the `GeoID` info should be set via configuration and that info had best follow a common path for all uses.  This means a shared `GeoID` schema and shared C++ helper to convert from config object to `GeoID` struct (which is hand written and not codegen'ed).  This commit will try to show the (a) way but some changes are out of scope.

**Comment by brettviren** [comment]
One immediate problem with introducing GeoID to `Set<T>` is that it is not serializable as required by `TPSet.hpp` and `TASet.hpp`.

**Comment by brettviren** [comment]
The `Set<T>::seqno` is 32 bits.  This will overflow in about 1 week at the rate of TPSet seen on a felix link in protodune.  Unless objection, I will make this 64bits as part of this issue.

**Comment by philiprodrigues** [comment]
> One immediate problem with introducing GeoID to `Set<T>` is that it is not serializable as required by `TPSet.hpp` and `TASet.hpp`.

The necessary magic for serializing GeoID is in dfmessages:

https://github.com/DUNE-DAQ/dfmessages/blob/develop/include/dfmessages/GeoID_serialization.hpp

so I think you should be able to just `#include` that file. (The serialization code isn't in dataformats because dataformats will eventually have to be shared with offline and so doesn't depend on other DAQ packages, in this case `serialization`)
