### ISSUE TITLE
Would it be possible to make the TriggerDecision ComponentRequest widths configurable?

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/trigger#55]
Hi,
I'm doing some tests of long-window readout code, and it would be convenient if I could change the width of the ComponentRequests that are sent out in the TriggerDecision via configuration.

This would affect the following line of code, I believe:

https://github.com/DUNE-DAQ/trigger/blob/c5e20db37b81889f825ce49940e40fed471bdaaf/plugins/ModuleLevelTrigger.cpp#L161

I'm not asking for anything fancy, just the use of a single config param in the calculation of the request.window_end for all components in the TD.

Thanks!

**Comment by philiprodrigues** [comment]
I've implemented fixes in the linked PRs. The trigger decision now takes its window start and end times from the input trigger candidate, and DUNE-DAQ/minidaqapp#62 makes the trigger candidate window directly settable from the confgen command line.
