### ISSUE TITLE
A few more ERS messages

### ISSUE THREAD

**Issue by glehmannmiotto** [DUNE-DAQ/trigger#60]
I think it would be useful to add the following ERS issues in the trigger package:
ERS_DECLARE_ISSUE(trigger, TriggerActive, "Trigger is active", ERS_EMPTY)
ERS_DECLARE_ISSUE(trigger, TriggerPaused, "Trigger is paused", ERS_EMPTY)
ERS_DECLARE_ISSUE(trigger, TriggerInhibited, "Trigger is inhibited", ERS_EMPTY)

and add the corresponding ers::info / ers::warning messages in the code.
I have no permission to push to this package.

**Comment by philiprodrigues** [comment]
Fixed by #61
