### ISSUE TITLE
`merge::latency` not set from configuration by `TriggerZipper`

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/trigger#68]
I think the `latency` parameter of `merge` is not being set by `TriggerZipper`

**Comment by brettviren** [comment]
I think you are right.

The underlying `zipper.hpp` needs a `merge::set_latency(duration_t latency)` method (akin to `set_cardinatlity()`) and then `TriggerZipper` needs to use it.

I am still with a broken development environment but I'll try to get to this soon.  If you happen to feel inspired, please feel free to make this change.
